name: Deployment

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  
  pull_request:    
    branches: [main]    
    types: [opened, synchronize]

permissions:
  contents: write
  
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test
      
  deploy:
    if: ${{ github.event_name == 'push' && !contains(toJson(github.event.commits.*.message),'#skip') }}
    needs: [checks]
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Install dependencies
        run: npm ci

      - name: Clean build
        run: rm -rf dist

      - name: Build
        run: npm run build

      - uses: actions/checkout@v4
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist

  tag_release:
    if: ${{ github.event_name == 'push' && !contains(toJson(github.event.commits.*.message),'#skip') }}
    needs: [deploy]
    permissions:
      contents: write
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
    